import Head from "next/head";
import Layout from "@/components/layout";
import StoreList from "@/components/Store";
import Header from "@/components/header";

export default function Home() {
  return (
    <>
      <Head>
        <title>SSEM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <StoreList />
      </Layout>
    </>
  );
}
